# Sample NMEA parameter configuration

nmea:
  set: true
  version: 65
  num_sv: 8
  sv_numbering: 1
  compat: true
  consider: true
  limit82: true
  high_prec: true
  filter:
    pos: false
    msk_pos: false
    time: false
    date: false
    gps_only: false
    track: false
  gnssToFilter:
    gps: false
    sbas: true
    qzss: false
    glonass: false
    beidou: false
  main_talker_id: 1
  gsv_talker_id: 1
  bds_talker_id: [0,0]